apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        flox.dev/environment: "flox/redis"
    spec:
      runtimeClassName: flox
      containers:
        # The following container is not used but is required by the
        # Kubernetes pod specification. Any valid values can be used here.
        - name: empty
          image: flox/empty:1.0.0
          # The following command is the command that is invoked by `flox activate`
          # to keep the environment alive. It can be used to perform supplementary
          # actions at startup, and when this command exits the pod is torn down.
          command: ["redis-server", "$REDISCONFIG", "--daemonize", "no", "--dir", "/data" ]
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}

