apiVersion: apps/v1
kind: Deployment
metadata:
  name: flox-containerd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flox-containerd-demo
  template:
    metadata:
      labels:
        app: flox-containerd-demo
      annotations:
        flox.dev/environment: "djsauble/simple-http-server"
    spec:
      runtimeClassName: flox
      # hostNetwork: true   # join the node's network namespace
      dnsPolicy: Default    # inherit the node's /etc/resolv.conf
      containers:
        # The following container is not used but is required by the
        # Kubernetes pod specification. Any valid values can be used here.
        - name: empty
          image: flox/empty:1.0.0
          # The following command is the command that is invoked by `flox activate`
          # to keep the environment alive. It can be used to perform supplementary
          # actions at startup, and when this command exits the pod is torn down.
          command: ["simple-http-server"]
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flox-containerd-demo
spec:
  type: NodePort
  selector:
    app: flox-containerd-demo
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
