apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
      annotations:
        flox.dev/environment: "flox/quotes-app"
    spec:
      runtimeClassName: flox
      containers:
        - name: quotes
          # We provide `flox/empty` as a demonstration that the Flox
          # environment requires nothing from the container image.
          image: flox/empty:1.0.0
          # The command to run inside your environment
          command: ["quotes-app-go", "-r", "redis:6379"]
---
apiVersion: v1
kind: Service
metadata:
  name: quotes
  labels:
    app: quotes
spec:
  type: ClusterIP
  selector:
    app: quotes
  ports:
    - name: quotes
      port: 3000
      targetPort: 3000
      protocol: TCP
