apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
      annotations:
        flox.dev/environment: "flox/quotes-app"
    spec:
      runtimeClassName: flox
      containers:
        # The following container is not used but is required by the
        # Kubernetes pod specification. Any valid values can be used here.
        - name: quotes
          image: flox/empty:1.0.0
          # The following command is the command that is invoked by `flox activate`
          # to keep the environment alive. It can be used to perform supplementary
          # actions at startup, and when this command exits the pod is torn down.
          command: ["quotes-app-go", "-r", "redis:6379"]
---
apiVersion: v1
kind: Service
metadata:
  name: quotes
  labels:
    app: quotes
spec:
  type: ClusterIP
  selector:
    app: quotes
  ports:
    - name: quotes
      port: 3000
      targetPort: 3000
      protocol: TCP
