version = 1

[install]
kind.pkg-path = "kind"
k9s.pkg-path = "k9s"
kubectl.pkg-path = "kubectl"
kubectx.pkg-path = "kubectx"
iptables.pkg-path = "iptables"
iptables.systems = ["aarch64-linux", "x86_64-linux"]
podman.pkg-path = "podman"
podman.systems = ["aarch64-linux", "x86_64-linux"]
gh.pkg-path = "gh"
just.pkg-path = "just"
colima.pkg-path = "colima"
